server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WeChat_App?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
#  type-aliases-package: com.ffl.ahydboot.bean
#  mapper-locations: classpath*:mapper/*.xml
  mapperLocations: classpath*:mapper/*.xml

#showSql
logging:
  level:
    com.ffl.myapp01boot.mapper: DEBUG
